#!/usr/bin/env bash
# The interoperability run against Bob Beck's Go stack (`mtc`, from
# github.com/bob-beck/cloudflare-mtc) and the OpenSSL of PR openssl/openssl#33014.
# Usage: OPENSSL=... OPENSSL_SRC=... MTC=... interop/run-openssl.sh OUTDIR
#   OPENSSL      the `openssl` binary built from the PR (with LD_LIBRARY_PATH
#                set, if it is not installed system-wide)
#   OPENSSL_SRC  that source tree (its test/mtc corpus is read)
#   MTC          the `mtc` binary built from Bob Beck's repository
#   MTC_SRC      optional: that checkout, to record its commit
# Requires: cargo, python3. Writes OUTDIR/results.txt and exits non-zero if
# any comparison differs.
set -euo pipefail

OUT="${1:?usage: OPENSSL=... OPENSSL_SRC=... MTC=... interop/run-openssl.sh OUTDIR}"
OPENSSL="${OPENSSL:?set OPENSSL to the openssl binary built from openssl/openssl#33014}"
OPENSSL_SRC="${OPENSSL_SRC:?set OPENSSL_SRC to that source tree}"
MTC="${MTC:?set MTC to the mtc binary of github.com/bob-beck/cloudflare-mtc}"
"$OPENSSL" version >/dev/null || { echo "$OPENSSL does not run (LD_LIBRARY_PATH?)" >&2; exit 2; }
[ -d "$OPENSSL_SRC/test/mtc" ] || { echo "no test/mtc in $OPENSSL_SRC" >&2; exit 2; }
[ -x "$MTC" ] || { echo "no mtc binary at $MTC (build it with Go 1.27 or later: cd cloudflare-mtc && go build -o mtc ./cmd/mtc)" >&2; exit 2; }
"$MTC" --help >/dev/null 2>&1 || { echo "$MTC does not run" >&2; exit 2; }
command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 2; }
# The commit is the binary's own, as Go recorded it at build time; the
# checkout's HEAD may have moved since (AUDIT.md §23).
MTC_REV=$(go version -m "$MTC" 2>/dev/null | sed -n 's/^[[:space:]]*build[[:space:]]*vcs.revision=//p' || true)
MTC_HEAD=$(git -C "${MTC_SRC:-/nonexistent}" rev-parse HEAD 2>/dev/null || true)
if [ -n "$MTC_REV" ] && [ -n "$MTC_HEAD" ] && [ "$MTC_REV" != "$MTC_HEAD" ]; then
  echo "$MTC was built from $MTC_REV, but $MTC_SRC is at $MTC_HEAD: rebuild it (go build -o mtc ./cmd/mtc)" >&2; exit 2
fi
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FLIP="$ROOT/interop/flip.py"
mkdir -p "$OUT"
OUT="$(cd "$OUT" && pwd)"
RESULTS="$OUT/results.txt"
: > "$RESULTS"
FAILURES=0
MIRROR_PID=
trap '[ -n "$MIRROR_PID" ] && kill "$MIRROR_PID" 2>/dev/null || true' EXIT

say() { echo "$*" | tee -a "$RESULTS"; }
# One "file OK|FAIL" line per certificate, from either verifier's output
# (paths are absolute, so a verdict line starts with '/').
verdict() { grep '^/' | sed -E 's/^([^:]*): OK(:.*)?$/\1 OK/; t; s/^([^:]*): .*$/\1 FAIL/' | sed -E 's#^.*/##' | sort -V; }
# Compares two verdict files; on a difference, keeps the diff and counts it.
same() { # LABEL A B
  local d; d="diff-$(echo "$1" | tr -c 'A-Za-z0-9.+-' _ | sed 's/_*$//').txt"
  if diff -u "$2" "$3" > "$OUT/$d"; then
    say "$1: same verdict for all $(wc -l < "$2") certificates ($(grep -c ' OK$' "$2" || true) OK, $(grep -c ' FAIL$' "$2" || true) FAIL)"
  else
    say "$1: DIFFERENT verdicts, see $d"; FAILURES=$((FAILURES+1))
  fi
}

say "# mtc-core interoperability run against Bob Beck's mtc and OpenSSL, $(date -u +%Y-%m-%dT%H:%M:%SZ)"
say "openssl: $("$OPENSSL" version) at $(git -C "$OPENSSL_SRC" rev-parse HEAD 2>/dev/null || echo unknown)"
say "mtc: ${MTC_REV:-${MTC_HEAD:-commit not recorded (set MTC_SRC, or put go on PATH)}}"
say "rust: $(rustc --version), $(cargo --version)"
say "mtc-core: $(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"

(cd "$ROOT" && cargo build --release --example interop >/dev/null 2>&1) ||
  { echo "cargo build --release --example interop failed in $ROOT" >&2; exit 2; }
INTEROP="$ROOT/target/release/examples/interop"

# The TLS key (ML-DSA-44, generated by OpenSSL) and a fallback certificate
# for the server, which it sends when no MTC credential matches.
"$OPENSSL" genpkey -algorithm ML-DSA-44 -out "$OUT/tls-key.pem"
"$OPENSSL" pkey -in "$OUT/tls-key.pem" -pubout -out "$OUT/tls-pub.pem"
"$OPENSSL" genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out "$OUT/fallback-key.pem"
"$OPENSSL" req -x509 -key "$OUT/fallback-key.pem" -out "$OUT/fallback.pem" -days 2 \
  -subj /CN=fallback -config /dev/null 2>/dev/null

# ── 1. mtc-core → Bob's verifier ──
say ""
say "## 1. mtc-core -> mtc verify"
for OIDS in iana experimental-06; do
  R="$OUT/rust-$OIDS"; rm -rf "$R"
  "$INTEROP" generate -out "$R" -oids "$OIDS" -tls-key "$OUT/tls-pub.pem" > "$R.log"
  { grep -v '^#' "$R/EXPECTED.txt" | awk '{print $1, $2}'
    printf '%s\n' "tls_standalone.pem OK" "tls_standalone_caonly.pem FAIL" \
      "tls_standalone_bitflip.pem FAIL" "tls_landmark.pem OK" "tls_landmark_bitflip.pem FAIL"
  } | sort -V > "$R/expected.txt"
  "$MTC" verify --ca-cert "$R/ca_cert.pem" --cosigner-cert "$R/cosigners.pem" --quorum 1 \
    --subtrees "$R/subtrees.txt" "$R"/cert_*.pem "$R"/tls_*.pem 2>&1 | verdict > "$R/bob.txt" || true
  "$INTEROP" verify -ca-cert "$R/ca_cert.pem" -cosigner-cert "$R/cosigners.pem" -require 32473.3.1 \
    -subtrees "$R/subtrees.txt" "$R"/cert_*.pem "$R"/tls_*.pem 2>/dev/null | verdict > "$R/core.txt" || true
  same "$OIDS OIDs, mtc verify against the expected verdicts" "$R/expected.txt" "$R/bob.txt"
  same "$OIDS OIDs, mtc-core on the same OpenSSL-format inputs" "$R/expected.txt" "$R/core.txt"
done

# ── 2. Bob's CA → mtc-core ──
say ""
say "## 2. mtc's CA (with a mirror) -> mtc-core"
B="$OUT/bob"; rm -rf "$B"; mkdir -p "$B/keys" "$B/neg"
PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1])')
"$MTC" ca -p "$B/ca" new --log 1 --max-lifetime 168h --landmark-interval 1s 32473.1 > "$B/setup.log"
"$MTC" mirror -p "$B/mirror" new 32473.2 >> "$B/setup.log"
"$MTC" mirror -p "$B/mirror" add-log --log 1 "$B/ca/ca-cert.pem" >> "$B/setup.log"
"$MTC" mirror -p "$B/mirror" serve --listen "localhost:$PORT" > "$B/mirror.log" 2>&1 &
MIRROR_PID=$!
for _ in $(seq 50); do grep -q serving "$B/mirror.log" && break; sleep 0.1; done
"$MTC" ca -p "$B/ca" add-mirror --required "http://localhost:$PORT" "$B/mirror/cosigner-cert.pem" >> "$B/setup.log"
q() { "$MTC" ca -p "$B/ca" queue --generate-key "$1" --key "$B/keys/k$2.pem" --dns "b$2.example" >/dev/null; }
for i in 1 2 3 4 5; do q p256 $i; done; q mldsa44 6
"$MTC" ca -p "$B/ca" issue > "$B/issue.log"; sleep 2
for i in 7 8 9; do q p256 $i; done
"$MTC" ca -p "$B/ca" issue >> "$B/issue.log"; sleep 2
q p256 10
"$MTC" ca -p "$B/ca" issue >> "$B/issue.log"
kill "$MIRROR_PID"; MIRROR_PID=
"$MTC" ca -p "$B/ca" export-openssl -o "$B/ossl" > /dev/null
# Negatives, derived at the byte level by flip.py (no MTC code): entry 0's
# subtree [0, 4) has a two-hash inclusion proof and two cosignatures (the
# CA's, then the mirror's).
python3 "$FLIP" proof "$B/ca/certs/1/0.pem" "$B/neg/0_standalone_bitflip.pem"
python3 "$FLIP" proof "$B/ca/certs/1/0-landmark-1.pem" "$B/neg/0_landmark_bitflip.pem"
python3 "$FLIP" sig 0 "$B/ca/certs/1/0.pem" "$B/neg/0_standalone_ca_sig_flip.pem"
python3 "$FLIP" sig 1 "$B/ca/certs/1/0.pem" "$B/neg/0_standalone_mirror_sig_flip.pem"
sed -E '/^32473.1 1 0 4 /s/ [A-Za-z0-9+\/]([A-Za-z0-9+\/]*=)$/ A\1/' "$B/ossl/subtrees-1.txt" > "$B/neg/subtrees-wrong.txt"
cmp -s "$B/ossl/subtrees-1.txt" "$B/neg/subtrees-wrong.txt" && { say "the wrong-hash subtree file is not wrong"; FAILURES=$((FAILURES+1)); }
N=$(ls "$B"/ca/certs/1/*.pem | wc -l)
say "issued: $N certificates ($(ls "$B"/ca/certs/1/*-landmark-*.pem | wc -l) landmark-relative), $(grep -c '^landmark' "$B/issue.log") landmarks; $(ls "$B"/neg/*.pem | wc -l) negatives derived"
CERTS=("$B"/ca/certs/1/*.pem "$B"/neg/*.pem)
CA=(--ca-cert "$B/ossl/ca-cert.pem"); CORE_CA=(-ca-cert "$B/ossl/ca-cert.pem")
case_b() { # LABEL BOB-ARGS... -- CORE-ARGS...
  local label=$1; shift; local bob=() core=()
  while [ "$1" != -- ]; do bob+=("$1"); shift; done; shift; core=("$@")
  "$MTC" verify "${CA[@]}" ${bob[@]+"${bob[@]}"} "${CERTS[@]}" 2>&1 | verdict > "$B/bob-$label.txt" || true
  "$INTEROP" verify "${CORE_CA[@]}" ${core[@]+"${core[@]}"} "${CERTS[@]}" 2>/dev/null | verdict > "$B/core-$label.txt" || true
  same "$label: mtc-core against mtc verify" "$B/bob-$label.txt" "$B/core-$label.txt"
}
case_b subtrees+mirror --subtrees "$B/ossl/subtrees-1.txt" --cosigner-cert "$B/ossl/cosigners.pem" --quorum 1 \
  -- -subtrees "$B/ossl/subtrees-1.txt" -cosigner-cert "$B/ossl/cosigners.pem" -require 32473.2
if [ "$(grep -cE '^[0-9]+(-landmark-[0-9]+)?\.pem OK$' "$B/core-subtrees+mirror.txt" || true)" -eq "$N" ] &&
   [ "$(grep -c '_bitflip\.pem FAIL$' "$B/core-subtrees+mirror.txt" || true)" -eq 2 ]; then
  say "  every certificate the CA issued verifies; each bit flip of a proof fails"
else
  say "  NOT every issued certificate verifies, or a flipped proof passes"; FAILURES=$((FAILURES+1))
fi
case_b mirror --cosigner-cert "$B/ossl/cosigners.pem" --quorum 1 \
  -- -cosigner-cert "$B/ossl/cosigners.pem" -require 32473.2
case_b ca-only --
case_b wrong-subtree-hash --subtrees "$B/neg/subtrees-wrong.txt" -- -subtrees "$B/neg/subtrees-wrong.txt"
say "  (with the subtrees, a cosignature is not read: every standalone subtree of this CA is also a landmark's)"

# ── 3. mtc-core → OpenSSL, over TLS 1.3 ──
say ""
say "## 3. mtc-core -> openssl s_client, through openssl s_server"
# Decorates mtc-core's certificates with OpenSSL's own tool, as the draft's
# section 8.2.1 says (tls_chains.txt has the arguments).
chains() { # DIR
  mkdir -p "$1/chains"
  while read -r f args; do
    case "$f" in \#*|"") continue;; esac
    # shellcheck disable=SC2086
    "$OPENSSL" generate_tai_chain -chain "$1/$f" $args -out "$1/chains/$f"
  done < "$1/tls_chains.txt"
}
# One handshake: the server holds CHAINS, the client the rest. Prints the
# certificate served and s_client's verify result, and checks both.
tls() { # DIR NAME EXPECT(OK|FAIL) SERVED CHAINS -- CLIENT-ARGS...
  local d=$1 name=$2 expect=$3 served=$4 chains=$5; shift 6
  local log="$d/log/$name"; mkdir -p "$d/log"
  "$OPENSSL" s_server -accept 0 -naccept 1 -cert "$OUT/fallback.pem" -key "$OUT/fallback-key.pem" \
    -tai_chains "$chains" -tai_keys "$OUT/tls-key.pem" -tls1_3 -www > "$log.srv" 2>&1 &
  local spid=$! port=
  for _ in $(seq 100); do
    port=$(sed -n 's/^ACCEPT .*:\([0-9]*\)$/\1/p' "$log.srv"); [ -n "$port" ] && break; sleep 0.1
  done
  "$OPENSSL" s_client -connect "localhost:$port" -no-CAfile -no-CApath -no-CAstore -tls1_3 "$@" \
    < /dev/null > "$log.cli" 2>&1 || true
  wait "$spid" 2>/dev/null || true
  local code msg got=- v=FAIL status=ok
  code=$(sed -n 's/^Verify return code: \([0-9]*\).*/\1/p' "$log.cli" | tail -1)
  msg=$(sed -n 's/^Verify return code: //p' "$log.cli" | tail -1)
  sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/{p;/-----END/q}' "$log.cli" > "$log.peer.pem"
  for f in "$d"/tls_*.pem "$OUT/fallback.pem"; do
    if [ -s "$log.peer.pem" ] && cmp -s <("$OPENSSL" x509 -in "$log.peer.pem" -outform DER) \
         <("$OPENSSL" x509 -in "$f" -outform DER); then got=$(basename "$f"); fi
  done
  [ "$code" = 0 ] && v=OK
  # No certificate from the server means no verification took place (s_client
  # then still prints "Verify return code: 0"): an error of the run.
  [ -s "$log.peer.pem" ] || v=NO-HANDSHAKE
  { [ "$v" = "$expect" ] && [ "$got" = "$served" ]; } || { status=MISMATCH; FAILURES=$((FAILURES+1)); }
  say "$(printf '  %-22s served %-27s verify %s; expected %s from %s: %s' "$name" "$got" "${msg:-none}" "$expect" "$served" "$status")"
}
for OIDS in iana experimental-06; do
  R="$OUT/rust-$OIDS"; chains "$R"; C="$R/chains"
  L=(-mtc_landmarks "32473.1:1:$R/landmarks.txt" -mtc_subtrees "$R/subtrees.txt")
  cat "$C/tls_landmark.pem" "$C/tls_standalone.pem" > "$R/good.pem"
  cat "$C/tls_landmark_bitflip.pem" "$C/tls_standalone.pem" > "$R/landmark-bitflip.pem"
  sed -E '/^32473.1 1 16 21 /s/ [A-Za-z0-9+\/]([A-Za-z0-9+\/]*=)$/ A\1/' "$R/subtrees.txt" > "$R/subtrees-wrong.txt"
  say "$OIDS OIDs:"
  tls "$R" standalone OK tls_standalone.pem "$R/good.pem" -- -mtc_cas "$R/ca_cert.pem"
  tls "$R" landmark OK tls_landmark.pem "$R/good.pem" -- -mtc_cas "$R/ca_cert.pem" "${L[@]}"
  [ "$OIDS" = iana ] || continue
  tls "$R" standalone-quorum-1 OK tls_standalone.pem "$R/good.pem" -- -mtc_cas "$R/ca_cert.pem" \
    -mtc_cosigners "$R/cosigners.pem" -mtc_cosigner_quorum 1
  tls "$R" ca-only-quorum-0 OK tls_standalone_caonly.pem "$C/tls_standalone_caonly.pem" -- -mtc_cas "$R/ca_cert.pem"
  tls "$R" ca-only-quorum-1 FAIL tls_standalone_caonly.pem "$C/tls_standalone_caonly.pem" -- -mtc_cas "$R/ca_cert.pem" \
    -mtc_cosigners "$R/cosigners.pem" -mtc_cosigner_quorum 1
  tls "$R" standalone-bitflip FAIL tls_standalone_bitflip.pem "$C/tls_standalone_bitflip.pem" -- -mtc_cas "$R/ca_cert.pem"
  tls "$R" landmark-bitflip FAIL tls_landmark_bitflip.pem "$R/landmark-bitflip.pem" -- -mtc_cas "$R/ca_cert.pem" "${L[@]}"
  tls "$R" landmark-wrong-hash FAIL tls_landmark.pem "$R/good.pem" -- -mtc_cas "$R/ca_cert.pem" \
    -mtc_landmarks "32473.1:1:$R/landmarks.txt" -mtc_subtrees "$R/subtrees-wrong.txt"
  tls "$R" other-ca-same-id FAIL tls_standalone.pem "$R/good.pem" -- -mtc_cas "$B/ossl/ca-cert.pem"
done

# ── 4. OpenSSL's corpus → mtc-core ──
say ""
say "## 4. OpenSSL's test/mtc corpus -> mtc-core, against mtc verify"
T="$OPENSSL_SRC/test/mtc"; D="$OUT/openssl-corpus"; rm -rf "$D"; mkdir -p "$D"
cat "$T"/mtc-landmark-*-subtrees.txt | sort -u > "$D/subtrees.txt"
mapfile -t OC < <(ls "$T"/mtc-*.pem | grep -Ev '/mtc-(ca-cert|cosigners?(-[0-9.]+)?|crl-.*|landmark-key|server-key)\.pem$')
# The fixtures are valid 2020..2030; OpenSSL's tests verify at 2025-01-01.
"$MTC" verify --ca-cert "$T/mtc-ca-cert.pem" --cosigner-cert "$T/mtc-cosigners.pem" \
  --subtrees "$D/subtrees.txt" --now 2025-01-01T00:00:00Z "${OC[@]}" 2>&1 | verdict > "$D/bob.txt" || true
"$INTEROP" verify -ca-cert "$T/mtc-ca-cert.pem" -cosigner-cert "$T/mtc-cosigners.pem" \
  -subtrees "$D/subtrees.txt" -now 1735689600 "${OC[@]}" 2>/dev/null | verdict > "$D/core.txt" || true
# The one known difference (AUDIT §19): a certificate with the IANA
# id-alg-mtcProof and the experimental trustAnchorID issuer, which OpenSSL
# and mtc accept field by field and this crate refuses (one set per certificate).
KNOWN="mtc-landmark-1-iana-alg.pem"
grep -v "^$KNOWN " "$D/bob.txt" > "$D/bob-rest.txt"
grep -v "^$KNOWN " "$D/core.txt" > "$D/core-rest.txt"
same "the corpus except $KNOWN" "$D/bob-rest.txt" "$D/core-rest.txt"
say "  $KNOWN: mtc verify $(grep "^$KNOWN " "$D/bob.txt" | cut -d' ' -f2), mtc-core $(grep "^$KNOWN " "$D/core.txt" | cut -d' ' -f2) (known: mixed OID sets)"
if [ "$(grep "^$KNOWN " "$D/core.txt" | cut -d' ' -f2)" != FAIL ]; then
  say "  the known difference has changed: look again"; FAILURES=$((FAILURES+1))
fi

say ""
say "failures: $FAILURES"
exit $FAILURES
